# Generated by Django 3.2.7 on 2021-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0002_rename_user_grequouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='grequouser',
            name='password',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grequouser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
