# Generated by Django 3.2.7 on 2021-09-13 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0003_auto_20210913_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='grequouser',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
