# Generated by Django 3.2.7 on 2021-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0005_auto_20210913_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grequouser',
            name='id',
        ),
        migrations.AddField(
            model_name='grequouser',
            name='user_id',
            field=models.AutoField(default=12345, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
