# Generated by Django 3.2.7 on 2021-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0006_auto_20210914_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grequouser',
            name='user_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
