# Generated by Django 3.2.7 on 2021-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0007_alter_grequouser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grequouser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='grequouser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1232, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
