# Generated by Django 3.2.7 on 2021-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0008_auto_20210914_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='grequouser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
