# Generated by Django 3.2.7 on 2021-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0009_grequouser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grequouser',
            name='id',
        ),
        migrations.AddField(
            model_name='grequouser',
            name='user_id',
            field=models.AutoField(auto_created=True, default=1223, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
