# Generated by Django 3.2.7 on 2021-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0010_auto_20210914_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grequouser',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
