# Generated by Django 3.2.7 on 2021-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0014_auto_20210916_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='testoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abcd', models.TextField(max_length=300)),
            ],
        ),
    ]
