# Generated by Django 3.2.7 on 2021-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0016_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
