# Generated by Django 3.2.7 on 2021-09-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0019_userquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userquestion',
        ),
    ]
