# Generated by Django 3.2.7 on 2021-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0020_delete_userquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questasked', models.TextField(max_length=300)),
            ],
        ),
    ]
