# Generated by Django 3.2.7 on 2021-09-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0021_userquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testoo',
            name='abcd',
        ),
    ]
