# Generated by Django 3.2.7 on 2021-09-16 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0022_remove_testoo_abcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
