# Generated by Django 3.2.7 on 2021-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0023_testoo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoo',
            name='abcd',
            field=models.TextField(default='', max_length=300),
        ),
    ]
