# Generated by Django 3.2.7 on 2021-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0024_testoo_abcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testoo',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
