# Generated by Django 3.2.7 on 2021-09-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0030_auto_20210916_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abcdef',
        ),
    ]
