# Generated by Django 3.2.7 on 2021-09-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0033_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='post_id',
        ),
    ]
