# Generated by Django 3.2.7 on 2021-09-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0034_remove_usercomment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GrequoApp.userquest'),
            preserve_default=False,
        ),
    ]
