# Generated by Django 3.2.7 on 2021-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0035_usercomment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
