# Generated by Django 3.2.7 on 2021-09-16 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0036_alter_usercomment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='post_id',
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
