# Generated by Django 3.2.7 on 2021-09-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0037_auto_20210917_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercomment',
        ),
    ]
