# Generated by Django 3.2.7 on 2021-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0039_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_author',
            field=models.CharField(default='', max_length=30),
        ),
    ]
