# Generated by Django 3.2.7 on 2021-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrequoApp', '0043_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='is_disliked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='is_liked',
            field=models.BooleanField(null=True),
        ),
    ]
